### ISSUE TITLE
use another file than oxygen.conf.js

### ISSUE THREAD

**Issue by wokier** [oxygenhq/oxygen#260]
Hi

The documentation state that it is possible to use another file than oxygen.conf.js
https://docs.oxygenhq.org/download-installation-start/start-working-with-oxygen/introduction-and-usage
oxygen [OPTIONS]... FILE
But by doing that the tests are not read properly , and only a report with 0 tests is generated.
There is no difference between the 2 files except the test suite.
The same file with another name would also gives this strange result.

I see a difference in the logs
oxygen --ro=/mnt/tests/reports oxygen.conf.js (OK case)
    Suite "Module A - Screen 1 - My Test Suite" has started...
      - Case "Screen 1 - My Test Case " has started...
			
oxygen --ro=/mnt/tests/reports recevabilite.conf.js (KO case)
    Suite "recevabilite.conf" has started...
      - Case "recevabilite.conf" has started...

So the report contains this informations:
Total Tests 1
Passed Tests 1
Tests / Devices / Browsers
Test Name	Device / Browser	Platform	Pass/Failed Cases	Status
recevabilite.conf	Chrome		
100% (1)0% (0)	PASSED
Detailed Results
Item
recevabilite.conf (Iteration #1)
recevabilite.conf (Iteration #1) PASSED
Steps
Step	Duration	Status	Details
- No steps defined -

(recevabilite is a french word for surface testing)

Another minor difference is that the report is not generated at the same place
oxygen --ro=/mnt/tests/reports oxygen.conf.js (OK case)
generates the report at reports/report.html			

oxygen --ro=/mnt/tests/reports recevabilite.conf.js (KO case)
generates the report at reports/2022-04-11_103136/report.html	 (path contains datetime of the execution)

Observed in versions 1.19.1 and 1.22.0

**Comment by erandame** [comment]
Checking this, will get back to you

**Comment by romovs** [comment]
Hi wokier,

There are two ways to execute tests:

1. Using project configuration file oxygen.conf.js. This file that should be named exactly like this and should contain the project configuration.
2. Passing a single script directly. Basically any other file than oxygen.conf.js is considered by Oxygen as a test script.

So when you pass oxygen.conf.js it reads the configuration and executes tests defined within. If oxygen.conf.js has  `reporting.outputDir` set then the report will be saved at the specified path (the missing datetime subfolder seems like a bug). `--ro` option is ignored when executing via oxygen.conf.js file.
 
When you pass any other file, then Oxygen assumes that it's a test script and starts executing it directly. That is, it expects this file to be the actual test script instead of a project configuration. `--ro` option is not ignored in this case

**Comment by wokier** [comment]
The workaround we used is to copy the desired file into oxygen.conf.js before running oxygen.
